version: '3'

services:
	trade_dev:
		build: under-testing
	    image: 'luigymach/trade_dev:1.3.0'
	    command: 
	    user: docker
	    deploy:
	      resources:
	        reservations:
	          devices:
	          - driver: nvidia
	            device_ids: ['0']
	            capabilities: [gpu]


		volumes:
		    - "$(MYDIR):/home/docker/TrADe"
		    - "/tmp/.X11-unix:/tmp/.X11-unix"
		environment:
		    - DISPLAY=$DISPLAY
		stdin_open: true
		tty: true

