version: '3'

services:
	trade_dev:
		container_name: trade 
		build: 
			context: ./docker
			dockerfile: Dockerfile
	    image: 'luigymach/trade_dev:1.3.0'
		volumes:
			- "$(ORI_TRADE_DIR):$(DES_TRADE_DIR)"
			- "$(UNIX_DOMAIN_SOCKET):$(UNIX_DOMAIN_SOCKET)"

	    command: /bin/bash cd DES_TRADE_DIR
	    user: $(USER_CONTAINER)
		environment:
		    - DISPLAY=$DISPLAY
		stdin_open: true
		tty: true

	    deploy:
	      resources:
	        reservations:
	          devices:
	          - driver: nvidia
	            device_ids: ['0']
	            capabilities: [gpu]
