version: '3'

services:
  trade_dev:
    container_name: trade 
    
    build: 
      context:$${DOCKER_DIR}
      dockerfile:Dockerfile
    
    image: 'luigymach/trade_dev:1.3.0'
    
    volumes:
      - $${ORI_TRADE_DIR}:$${DES_TRADE_DIR}
      - $${UNIX_DOMAIN_SOCKET}:$${UNIX_DOMAIN_SOCKET}
    
    command: '/bin/bash '
    
    user: $${USER_CTR}
    
    environment:
      - DISPLAY=$${DISPLAY}
    stdin_open: true
    tty: true
    devices:
      - /dev/nvidia0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    


